{"name": "test_mp_login[13812345678-\\u767e\\u5ea6\\u4e00\\u4e0b]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../image/err1.png'", "trace": "self = <script.Test03_mp_login.TestMpLogin object at 0x000002BD9E4B73A0>, username = '13812345678', expect = '百度一下'\n\n    @pytest.mark.parametrize(\"username,expect\", read_yaml(\"mp_login.yaml\"))  # 参数化运行\n    def test_mp_login(self, username, expect):\n        self.mp.page_mp_login(username)\n        # print(\"\\n 获取的昵称为：\",self.mp.page_get_nickname())\n        try:\n            # assert expect == self.mp.page_get_nickname()\n>           assert expect ==\"百度一下1\"\nE           AssertionError: assert '百度一下' == '百度一下1'\nE             - 百度一下1\nE             ?     -\nE             + 百度一下\n\nscript\\Test03_mp_login.py:34: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <script.Test03_mp_login.TestMpLogin object at 0x000002BD9E4B73A0>, username = '13812345678', expect = '百度一下'\n\n    @pytest.mark.parametrize(\"username,expect\", read_yaml(\"mp_login.yaml\"))  # 参数化运行\n    def test_mp_login(self, username, expect):\n        self.mp.page_mp_login(username)\n        # print(\"\\n 获取的昵称为：\",self.mp.page_get_nickname())\n        try:\n            # assert expect == self.mp.page_get_nickname()\n            assert expect ==\"百度一下1\"\n        except Exception as e:\n            log.error(\"断言出错，错误信息：{}\".format(e))\n            # print(\"错误原因：\",e)\n>           self.mp.base_get_image()\n\nscript\\Test03_mp_login.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nbase\\base.py:38: in base_get_image\n    self.__base_write_image()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page.page_mp_login.PageMpLogin object at 0x000002BD9E554280>\n\n    def __base_write_image(self):\n>       with open(\"../image/err1.png\",\"rb\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../image/err1.png'\n\nbase\\base.py:41: FileNotFoundError"}, "attachments": [{"name": "log", "source": "1a675cd7-0926-4d7f-aa63-1a76747203be-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'13812345678'"}, {"name": "expect", "value": "'百度一下'"}], "start": 1684638274357, "stop": 1684638276273, "uuid": "0f171685-e2a0-474b-8a68-f68112a2660e", "historyId": "82b905dc1d5446b74bf5b37d894facce", "testCaseId": "a75eac0f96524bcfe49d409470304190", "fullName": "script.Test03_mp_login.TestMpLogin#test_mp_login", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "Test03_mp_login"}, {"name": "subSuite", "value": "TestMpLogin"}, {"name": "host", "value": "DESKTOP-PHOC90F"}, {"name": "thread", "value": "5652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.Test03_mp_login"}]}