{"name": "test_mp_login[13812345678-\\u767e\\u5ea6\\u4e00\\u4e0b]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../image/err.png'", "trace": "self = <script.Test03_mp_login.TestMpLogin object at 0x000001C907BF7100>, username = '13812345678', expect = '百度一下'\n\n    @pytest.mark.parametrize(\"username,expect\", read_yaml(\"mp_login.yaml\"))  # 参数化运行\n    def test_mp_login(self, username, expect):\n        self.mp.page_mp_login(username)\n        # print(\"\\n 获取的昵称为：\",self.mp.page_get_nickname())\n        try:\n            # assert expect == self.mp.page_get_nickname()\n>           assert expect ==\"百度一下1\"\nE           AssertionError: assert '百度一下' == '百度一下1'\nE             - 百度一下1\nE             ?     -\nE             + 百度一下\n\nscript\\Test03_mp_login.py:34: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <script.Test03_mp_login.TestMpLogin object at 0x000001C907BF7100>, username = '13812345678', expect = '百度一下'\n\n    @pytest.mark.parametrize(\"username,expect\", read_yaml(\"mp_login.yaml\"))  # 参数化运行\n    def test_mp_login(self, username, expect):\n        self.mp.page_mp_login(username)\n        # print(\"\\n 获取的昵称为：\",self.mp.page_get_nickname())\n        try:\n            # assert expect == self.mp.page_get_nickname()\n            assert expect ==\"百度一下1\"\n        except Exception as e:\n            log.error(\"断言出错，错误信息：{}\".format(e))\n            # print(\"错误原因：\",e)\n>           self.mp.base_get_image()\n\nscript\\Test03_mp_login.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nbase\\base.py:38: in base_get_image\n    self.__base_write_image()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page.page_mp_login.PageMpLogin object at 0x000001C907BF7310>\n\n    def __base_write_image(self):\n>       with open(\"../image/err.png\",\"rb\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../image/err.png'\n\nbase\\base.py:41: FileNotFoundError"}, "attachments": [{"name": "log", "source": "be71f25a-1955-4ed6-bfa1-bde70d76e688-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'13812345678'"}, {"name": "expect", "value": "'百度一下'"}], "start": 1684637986379, "stop": 1684637988366, "uuid": "3798f8b0-776a-40de-ac3b-65054cb0a4d0", "historyId": "82b905dc1d5446b74bf5b37d894facce", "testCaseId": "a75eac0f96524bcfe49d409470304190", "fullName": "script.Test03_mp_login.TestMpLogin#test_mp_login", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "Test03_mp_login"}, {"name": "subSuite", "value": "TestMpLogin"}, {"name": "host", "value": "DESKTOP-PHOC90F"}, {"name": "thread", "value": "14956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.Test03_mp_login"}]}